#!/bin/bash

# Add the nuxeo repository to the repository list
echo "deb http://apt.nuxeo.org/ lucid releases" > /etc/apt/sources.list.d/nuxeo.list
# Register the nuxeo key
wget -q -O- http://apt.nuxeo.org/nuxeo.key | apt-key add -
# Add the partner repository (for java)
echo "deb http://archive.canonical.com/ubuntu lucid partner" >> /etc/apt/sources.list.d/nuxeo.list

# Pre-accept Sun Java license & set DM options
echo sun-java6-jdk shared/accepted-sun-dlj-v1-1 select true | debconf-set-selections
echo sun-java6-jre shared/accepted-sun-dlj-v1-1 select true | debconf-set-selections
echo nuxeo-dm nuxeo-dm/bind-address select 127.0.0.1 | debconf-set-selections
echo nuxeo-dm nuxeo-dm/http-port select 8080 | debconf-set-selections
echo nuxeo-dm nuxeo-dm/database select Autoconfigure PostgreSQL | debconf-set-selections

# Upgrade packages and install ssh, vim and nuxeo-dm
export DEBIAN_FRONTEND=noninteractive
aptitude update
aptitude -q -y safe-upgrade
aptitude -q -y install apache2
echo "Please wait a few minutes for you instance installation to complete" > /var/www/index.html
aptitude -q -y install openssh-server openssh-client vim nuxeo-dm

# Update some defaults
update-java-alternatives -s java-6-sun
update-alternatives --set editor /usr/bin/vim.basic

# Configure reverse-proxy
cat << EOF > /etc/apache2/sites-available/nuxeo-dm
<VirtualHost _default_:80>

    CustomLog /var/log/apache2/nuxeodm_access.log combined
    ErrorLog /var/log/apache2/nuxeodm_error.log

    DocumentRoot /var/www

    ProxyRequests Off
    <Proxy *>
        Order allow,deny
        Allow from all
    </Proxy>

    RewriteEngine On
    RewriteRule ^/$ /nuxeo/ [R,L]
    RewriteRule ^/nuxeo$ /nuxeo/ [R,L]

    ProxyPass        /nuxeo/ http://localhost:8080/nuxeo/
    ProxyPassReverse /nuxeo/ http://localhost:8080/nuxeo/
    ProxyPreserveHost On

    # WSS
    ProxyPass        /_vti_bin/     http://localhost:8080/_vti_bin/
    ProxyPass        /_vti_inf.html http://localhost:8080/_vti_inf.html
    ProxyPassReverse /_vti_bin/     http://localhost:8080/_vti_bin/
    ProxyPassReverse /_vti_inf.html http://localhost:8080/_vti_inf.html

</VirtualHost>
EOF

a2enmod proxy proxy_http rewrite
a2dissite default
a2ensite nuxeo-dm
apache2ctl -k graceful

